### ISSUE TITLE
How to model ticket information?

### ISSUE THREAD

**Issue by jplu** [3cixty/knowledgebase#64] opened 2015-05-11 14:26 UTC
In Evensi dataset (and I think in other as well) there is the ticket information, it is the website where you can buy tickets for the corresponding event.

In schema.org I didn't see any property representing this. Any idea on how to model this?

@rtroncy did you deal with that for eventmedia?

**Comment by rtroncy** [comment] 2015-05-11 14:35
Duplicate of issue #30

**Closed by rtroncy** 2015-05-11 14:35 UTC
Labels: enhancement
