### ISSUE TITLE
Move the load of prefixes in KBDeploy to the beginning

### ISSUE THREAD

**Issue by ocorcho** [3cixty/knowledgebase#59] opened 2015-05-05 16:18 UTC
It would be nicer to have the prefixes loaded at the beginning of the KBDeploy process so as to allow queries to be used in patches applied during the process not to include the list of prefixes.

**Comment by jplu** [comment] 2015-05-05 18:24
@ocorcho the prefixes are created just before executing the queries used as patches, so they can use thoses prefixes.

If you got an error that means that there is a missing prefix in the list. I will check the list once again.

**Comment by rtroncy** [comment] 2015-05-05 22:57
A good way to test is to remove **all** PREFIX declarations in the patch queries and run KBDeploy to see if errors are thrown.

@ocorcho, did you get an error for a specific PREFIX?

**Comment by ocorcho** [comment] 2015-05-05 23:14
PREFIX locn: <http://www.w3.org/ns/locn#>

**Comment by jplu** [comment] 2015-05-06 08:12
Ok I take care of that today.

**Comment by jplu** [comment] 2015-05-06 09:14
It is weird because the prefix ```locn``` is created:

```
DB.DBA.XML_SET_NS_DECL ('locn', 'http://www.w3.org/ns/locn#', 2)
```

**Comment by rtroncy** [comment] 2015-05-06 09:20
Correct, which is confirmed looking at the list of known prefixes on both [www](http://3cixty.eurecom.fr/sparql?nsdecl) and [beta](http://91.250.81.138:8890/sparql?nsdecl).

@ocorcho We don't really see where is the issue you have encountered. To further check, can @jplu modify the patch queries, removing all prefix declarations, committing/pushing the new queries and relaunching KBdeploy (on MediaMixer?) to see if errors are thrown?

**Comment by jplu** [comment] 2015-05-06 10:21
Ok I deleted all the prefix declarations from the patches and relaunch KBdeploy on my machine. Everything went well.

**Comment by rtroncy** [comment] 2015-05-06 12:16
Thanks. I'm closing therefore this issue. @ocorcho, please, re-open this issue if this pops-up again

**Closed by rtroncy** 2015-05-06 12:16 UTC
Labels: enhancement
